# از ریشهٔ مخزن اجرا شود:
# docker compose -f ../../../docker-compose.yml -f ../../../docker-compose.traefik.yml -f docker-compose.yml --env-file .env up -d

services:
  web:
    build:
      context: ../../../
      dockerfile: Dockerfile

  queue:
    build:
      context: ../../../
      dockerfile: Dockerfile

  scheduler:
    build:
      context: ../../../
      dockerfile: Dockerfile
